### ISSUE TITLE
Contao 4.6 - Internal Server Error

### ISSUE THREAD

**Issue by swiss-netwalk** [terminal42/contao-folderpage#13]
Nach dem Manager-Update von 4.5.x auf die 4.6 kriege ich eine Fehlermeldung sobald ich im Contao-BE die Artikel oder Seitenstruktur aufrufe:
`The service "terminal42_folderpage.datacontainer.page" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services`

Nach dem deinstallieren verhält sich das BE wieder richtig - ein nochmaliges installieren zeigt das gleiche Resultat. Das restliche BE funktioniert aber problemlos.

**Comment by aschempp** [comment]
Fehler ist in der Version 2.0.5 behoben 😎
