### ISSUE TITLE
Feature : Posibility to set the folder on- or offline

### ISSUE THREAD

**Issue by MacKP** [terminal42/contao-folderpage#16]
It would be nice, to set the visibility state of the folders.
The eye Button is already in the overfiew and it is possible to show the Folder in an Navigation. It would be consistent to have this feature.
Otherwise it would be nice to grey out the eye in the Overview ;-)

Kind regards

**Comment by aschempp** [comment]
Yeah, I still don't understand why one would show the folder in the navigation?

**Comment by MacKP** [comment]
I know what you mean. Sometimes it's handy for a drop-down Navigation where the Parent-Elements have no content (they are no Pages). And in that case it can be better to use Folder (expecialy for editors, because than there is no question about it).
But this ticket is more about consistency ore usability. When you can click it it should do the expectet thing. Ore there is nothing to click here ;-)
