### ISSUE TITLE
Think of "folderpage" not only as a Backend feature but also Frontend?

### ISSUE THREAD

**Issue by madmaharaja** [terminal42/contao-folderpage#18]
We are using this handy extension -- as pointed out in the readme.me -- in order to group pages in folders. When running into some "issues" and googling for solutions, I stumbled upon a few tickets and forum entries that made it clear to me what the (my) "problem" was and that I was not the only one experiencing this: 
The creators obviously intended to implement something that was solely meant to be a backend feature. Apparently there are a number of people though that would expect this extension also to have an effect on the frontend output – as all other page settings usually do. See e.g.:
https://github.com/terminal42/contao-folderpage/issues/2
https://github.com/terminal42/contao-folderpage/issues/8#issuecomment-309799358
https://github.com/terminal42/contao-folderpage/issues/9
https://github.com/terminal42/contao-folderpage/pull/11
https://github.com/terminal42/contao-folderpage/issues/14
https://github.com/terminal42/contao-folderpage/issues/16

My question would therefore be if it wouldn't make sense to tweak this extension so that it would also (at least optionally) have frontend/functional impacts? I am specifically thinking of:

- If you change a former „standard page” into a folder page: automatically redirect the former alias to the top page in the folder. Main reason for this: Links (internal and external) that are set to the old page (that now is a folder) would not result in a 404 error. And it might also solve this issue: https://github.com/terminal42/contao-folderpage/issues/9
- Based on the behaviour that was implemented here https://github.com/terminal42/contao-folderpage/pull/11, I think it would also make sense to optionally include the folder page as a sort of a (non-clickable) section header (with a css class) to the sitemap, breadcrumb navigation etc. This would also solve: https://github.com/terminal42/contao-folderpage/issues/2 and https://github.com/terminal42/contao-folderpage/issues/14
- One thing that imho is an actual issue, is the behaviour of when you deselect the option to “publish page” for folder pages. In the moment you save the changes, the folder page appears as published again. Of course you can work around this by selecting “hide from navigation” but try explaining this to around 100 editors “Well, sorry – I know it says you can unpublish those folder pages but it doesn’t do what it says.” Ideally I think it should be possible to actually deactivate a folder page (especially if one implements the other functionalities as proposed above) or it might be better to remove that option completely if it doesn’t do anything after all. I believe this is also what was addressed here: https://github.com/terminal42/contao-folderpage/issues/16

Anyway: We would be willing to co-finance the implementation of these changes if you deem them useful (depending on the price tag). What do you think?

**Comment by aschempp** [comment]
> In the moment you save the changes, the folder page appears as published again.

That looks like a bug to me, probably a leftover of when it was not possible to publish a folderpage.

Everything else is off the table for me. As you said, folderpage is mostly a backend feature to me. You can use the page in the frontend though, but you have to adjust the template accordingly. I don't want to add too many features to this very simple extension, feel free to implement something else e.g. for automatic frontend redirecting.
