### ISSUE TITLE
Impossible to create new root page

### ISSUE THREAD

**Issue by Xirdion** [terminal42/contao-folderpage#23]
With Contao 4.13 it is impossible to create another root page, when one already exists.

Error message:
`Contao\CoreBundle\Util\LocaleUtil::formatAsLocale(): Argument #1 ($languageTag) must be of type string, null given, called in vendor/contao/core-bundle/src/Routing/Page/PageRouting.php on line 46`

The problem is that the `rootLanguage` of the new page is used to set the `_locale`.
The `type` of the new page is *standard*, even though it should be a root page.

When using the PR of @fritzmg  #22 this error wont happen.

![image](https://user-images.githubusercontent.com/17783055/155324737-0a83a82e-ae00-4f94-99cf-748e9572990a.png)

**Comment by aschempp** [comment]
This should be fixed in 2.0.16 (d3cec08283c8aefe7805810db956b4905bfd99d3)
