### ISSUE TITLE
Folders get listed in the sitemap

### ISSUE THREAD

**Issue by rabauss** [terminal42/contao-folderpage#24]
Unfortunately after updating to contao 4.13 the folder pages are now listed with the page ID as alias in the `sitemap.xml`.
Can we prevent the listing of folder pages?

**Comment by aschempp** [comment]
Does it work if you switch the page type to `regular`, check the "exclude from sitemap" option and switch back to `folder`?

**Comment by rabauss** [comment]
Yes, one solution for me was now that I executed the following query:
```mysql
UPDATE `tl_page` SET `robots` = 'noindex,nofollow' WHERE `type` = 'folder'
```

**Comment by aschempp** [comment]
I guess that should go into our `save_callback` then 😊 
https://github.com/terminal42/contao-folderpage/blob/main/src/DataContainer/Page.php#L119
