### ISSUE TITLE
[v3] Support rendering in custom nav

### ISSUE THREAD

**Issue by rabauss** [terminal42/contao-folderpage#27]
Unfortunately in v3 it's not possible anymore to render folders in a custom nav.
It would be nice to have this support again for navs with javascript click events which should not have a link 😊

**Comment by denniserdmann** [comment]
Same here. I was wondering why in V3 the folders doesn't appear in frontend. Maybe a bug? (otherwise the template `nav_folderpage` should be removed too).

**Comment by aschempp** [comment]
I discussed a possible solution yesterday with @qzminski, I'll need to look into that

**Comment by rabauss** [comment]
What do we need to do, to support the rendering again?
Unfortunately, my `NoRobotsMigration` is only availabe in v3 and some folder links are in the sitemap of one project again...

**Comment by aschempp** [comment]
If I remember correctly, I discussed with @qzminski that we should use the `hide` flag of tl_page to dynamically set the path to `false` (an unroutable page). Not 100% sure this is possible, but if you would have the time to look into it and maybe do a PR that would help greatly 😊

**Comment by oexler** [comment]
What happens if the path parameter in the annotation is removed, so it is set to null instead of false.
This way it is not returned as an unroutable type.
In my tests it works again in custom nav. Does it have any drawbacks?
