### ISSUE TITLE
Keine Möglichkeit mehr zur direkten Erstellung von Artikeln in einem Ordner

### ISSUE THREAD

**Issue by BennyK80** [terminal42/contao-folderpage#31]
In in einer älteren Version (z.B. Version 2.0.6) ist es möglich, Artikel direkt in einem Ordner zu erstellen.

In der aktuellen Version (Version 3.0.2) ist dies nicht mehr möglich.

Würde mich freuen, wenn das wieder möglich wäre. 
Das erspart das Erstellen zusätzlicher (unnötiger) Seiten.

**Comment by aschempp** [comment]
Contao 4.13 kann unterscheiden zwischen Seiten die Inhalte haben/anzeigen, und Seiten die keine Inhalte anzeigen. Seiten ohne Inhalte können keine Artikel haben. Das gilt sowohl für Root-Seiten, Weiterleitungsseiten als auch Ordner-Seiten, da diese auf der Webseite nie aufgerufen werden können. Deshalb haben Ordner-Seiten keine Artikel.

Ich kann dir unsere Nodes-Erweiterung für "allgemeine" Inhalte empfehlen: https://extensions.contao.org/?p=terminal42%2Fcontao-node
