### ISSUE TITLE
Folderpages don't show up in navigation menus 

### ISSUE THREAD

**Issue by johannes-bittner** [terminal42/contao-folderpage#32]
Tested in a fresh Contao 4.13.20, PHP 8.0, folderpage 3.0.2 and folderpage 3.0.0: 
- pages with page type folderpage are not shown in the frontend anymore (regardless of the chosen navigation template in the navigation module)
- using folderpage 2.0.16, the extension works as expected

**Comment by fritzmg** [comment]
The issue is that Contao 4.13+ does not render menu items for "unroutable types" anymore and a folderpage is an unroutable type.

**Comment by johannes-bittner** [comment]
... but why does it work with Contao 4.13.20 and folderpage 2.0.16 then?

**Comment by aschempp** [comment]
duplicate of https://github.com/terminal42/contao-folderpage/issues/27
