### ISSUE TITLE
"Show hidden items" in navigation menu module doesn't work for folder pages

### ISSUE THREAD

**Issue by ericgerhardy** [terminal42/contao-folderpage#33]
Tested with Contao _4.13.24_, folderpage _3.1.0_ and PHP _8.1.13_.

A folderpage hidden trough the page structure via "hide in navigation" is not displayed even if the "show hidden items"-option is selected in the navigation menu module.

When the page type is changed to internal redirect, the page is displayed in the module.

Is this the desired behavior? 

_Additionally, there doesn't seem to be an SVG icon in the flexible-theme for a hidden folder page yet._

**Comment by aschempp** [comment]
Hmm, yes that is "desired" or how the module currently works. But I agree this might be strange.

**Comment by aschempp** [comment]
should be fixed by 17f50a2da2d90f43c9c14ecf872ce4c5f5920dac
