### ISSUE TITLE
Subfolders are not shown in navigation

### ISSUE THREAD

**Issue by denniserdmann** [terminal42/contao-folderpage#36]
Folderpage: 3.1.0
Contao: 4.13.26
Template: `nav_folderpage.html5`

When i use a combination of _folder_ (level 1), _subfolder_ (level 2) and _page_ (level 3), the upper folder is not shown in the menu. When i have a regular page in level 2, the upper folder is shown, but still not the subfolders. 

It looks like subfolders are not supported at the moment (in V2, it was working as expected).

**Comment by aschempp** [comment]
maybe related to https://github.com/terminal42/contao-folderpage/issues/34

does it work with the original `nav_default` template?

**Comment by aschempp** [comment]
should be fixed by 17f50a2da2d90f43c9c14ecf872ce4c5f5920dac
