### ISSUE TITLE
Cannot autowire service "Terminal42\FolderpageBundle\EventListener\PageBreadcrumbListener

### ISSUE THREAD

**Issue by MDevster** [terminal42/contao-folderpage#38]
I have tried to install contao/manager-bundle=5.4.0-RC1. Unfortunately, I get the following error message when running Contao Setup.

Error
```
> @php vendor/bin/contao-setup
In DefinitionErrorExceptionPass.php line 51:
                                                                               
  Cannot autowire service "Terminal42\FolderpageBundle\EventListener\PageBrea  
  dcrumbListener": argument "$security" of method "__construct()" has type "S  
  ymfony\Component\Security\Core\Security" but this class was not found.       
```

I could remove the service and set it up on BackendUser::getInstance(), if that's ok with you I'll do a PR.
Or do you have a better idea that it works with the service in 4.13 and 5.4?

**Comment by aschempp** [comment]
see https://github.com/terminal42/contao-folderpage/pull/40

**Comment by MDevster** [comment]
@aschempp Just for the sake of completeness, my solution would also have worked?

**Comment by aschempp** [comment]
Yes, sorry about that. The other PR actually didn't work (phpstan told me, but I ignored the CI chain 🙈 )
