### ISSUE TITLE
Warning: Undefined array key "tabindex" and Warning: Undefined array key "nofollow"

### ISSUE THREAD

**Issue by berecont** [terminal42/contao-folderpage#41]
Contao 5.3
Folder Page 3.2.3

Warning: Undefined array key "tabindex" 
Warning: Undefined array key "nofollow"

Beide Warnungen in `nav_folderpage.html5`
Mögliche Anpassungen bringen bie mir Abhilfe:
```
 <?php if (isset($item['tabindex']) && $item['tabindex']) echo ' tabindex="'.$item['tabindex'].'"'; ?>
 <?php if (isset($item['nofollow']) && $item['nofollow']) echo ' rel="nofollow"'; ?>
```

**Comment by aschempp** [comment]
Fixed in version 3.2.4
