### ISSUE TITLE
Aliashandling

### ISSUE THREAD

**Issue by cgpro** [terminal42/contao-folderpage#5]
Hi,

I want to use the extension for grouping menus like "mainnavigation", "headernavigation", "meta" and so on... 

The problem is, that the alias of the folder is displayed in the subpages and can't deleted after I switched the page type to an ordinary page. The alias is only blank, when changing a new page directly to the type "folder". 

The "problem" is, that the backenduser always have to edit the alias of a subpage within a folder (delete folder name from alias).

At initial setup of a new folderpage (without any alias saved in the database), the subpage-alias is getting a leading / (slash) domain.tld//sitename, this is a bug I think.

**Comment by aschempp** [comment]
So an empty alias would not solve that problem, right?

**Comment by cgpro** [comment]
If you save the page and change it to a folder, the new subpages within that folder are showing the alias of the folder. 

The alias must be empty (deleted) after changing to the page type folder. I tried it without saving and switching directly to type folder, but in this case the alias is not saved and the subpage is showing two slashed and the page can not accessed in the frontend.

**Comment by aschempp** [comment]
But you said even if the alias is empty, it would still add a slash for subpages?

**Comment by cgpro** [comment]
thats correct and one of the two problems ;-)

**Comment by aschempp** [comment]
So emptying the alias would not solve anything…

**Comment by dhe** [comment]
Hey, ich habe auch ein Anliegen in Sachen Aliasgenerierung.
Ich würde "folderpage" beliebig in meiner Struktur nutzen, um Seiten zu gruppieren (was es ja tut).
Allerdings habe ich ein Problem mit den Aliases in Kombination mit "Ordner-URLs".

Beispiel:
Seite 1A (seite-1a) (regular)
- Seite 2A (seite-1a/seite-2a) (regular)
- Seite 2B (seite-1a//) (folder)
-- Seite 3A (seite-1a//seite-3a) (regular)
-- Seite 3B (seite-1a//seite-3b) (regular)
-- Seite 3C (seite-1a//seite-3c) (regular)

Kann man die Alias-Generierung so einstellen, dass ein "Ordner" keinen leeren Alias bzw doppelte "/" erzeugt? geht so etwas?

Vielleicht wäre es auch ein Idee, bei Aufruf im Browser auf den Parent weiterzuleiten? 

Grüße

**Comment by qzminski** [comment]
I can confirm the issue that is having @dhe. When folder URLs setting is on the auto-generated alias has "/" in front and the page is not found:

```
- Foo -> folder
-- Bar [/bar] -> regular page
```

The Bar page can not be accessed until you manually change alias to ```bar```.

**Comment by dhe** [comment]
Ich hab mal folgendes in einer eigenen dcaconfig.php probiert
```php
$GLOBALS['TL_DCA']['tl_page']['fields']['alias']['save_callback'][] = array('tl_page_np', 'cleanAlias');
...
class tl_page_np extends \Backend {	
	public function cleanAlias($varValue, DataContainer $dc){	
		$strUrl = ltrim($varValue, '/');	
		return str_replace('//','/',$strUrl);	
	}
}

```
das entfernt mir doppelte Slashes bzw entfernt einzelne am Anfang. Klappt ganz gut.

**Comment by Toflar** [comment]
Was not that easy :-) Can you test 1132dac1f8c7b8595c831c8b82ec15f6e51355c6, please?
Or just install `hotfix/1.1.4` using Composer. It should clean up the aliases then :-)

**Comment by qzminski** [comment]
Fixed in ```hotfix/1.1.4```.
