### ISSUE TITLE
Duplicate alias problem

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-folderpage#6]
After we have implemented the ```hotfix/1.1.4``` which fixed folder page aliases issue (#5) a new problem appeared. The alias is not being checked for the duplicates. Given that we have this site structure:

- Home (alias: index)
- Contact (alias: contact)
- Folder 1 (type: folder)

It is possible to create a new page under the folder with a ```contact``` alias:

- Home (alias: index)
- Contact (alias: contact)
- Folder 1 (type: folder)
- |-- Contact (alias: contact)

And no "alias already exists" error will be thrown. That is because the alias cleanup is triggered after the default Contao callback which checks for duplicate alias. The process goes as follow (for above example):

1. Add new page Contact in/under Folder 1
2. The ```tl_page::generateAlias()``` is triggered. At this point the generates alias is ```/contact``` (slash because of parent folder) so it is unique.
3. The ```tl_page_folderpage::adjustAlias``` is triggered. At this point the alias ```/contact``` is being cleaned of the first slash. The returned value is ```contact```.
4. The new page has the ```contact``` value (duplicate).

Any proposals how to fix this? Perhaps it could work if we replace the default Contao callback but still use its code. So we would duplicate the highlighted code into our method:

https://github.com/contao/core/blob/master/system/modules/core/dca/tl_page.php#L962-L980

And once we have that alias generated pass it to ```tl_page::generateAlias()```. Not sure if it would work because of the ```$autoAlias``` though.

**Comment by Toflar** [comment]
Imho we cannot handle this on save. It's too complicated. What do you think about executing the cleanup on `showAll()` (just like reviseTable) and after cleanup, check for duplicates and show an error message just like you'll get if you did not specify a fallback page for example?

**Comment by qzminski** [comment]
That would work however it has a serious usability flaw because I can no longer fully use the Contao alias generate routine. Every alias duplicate I would need to correct manually.

**Comment by Toflar** [comment]
Only those that are within a folder page?

**Comment by qzminski** [comment]
Yes.

**Comment by Toflar** [comment]
Doesn't matter to me, really. Do you think it's better to generate something like `contact-533` automatically? We could btw still do that in my version. Duplicates can only occur in sub pages of folder page (others are caught by the callback of Contao) so we automatically fix them by adding the page ID?

**Comment by aschempp** [comment]
Why not just trigger the core callback again after we generated our name?

**Comment by qzminski** [comment]
Because then the ```$autoAlias``` flag is set to true and we lose access e.g. to appending the ID instead of throwing an error.

https://github.com/contao/core/blob/master/system/modules/core/dca/tl_page.php#L1034

**Comment by aschempp** [comment]
Why would it be set to true. That only happens if the value is empty, which it is not of we pass our value.

**Comment by qzminski** [comment]
So if we would pass our value then the ```$autoAlias``` is set to false and we would get an alias exists error. Would be better if Contao could handle it its default way, i.e. add the ID on duplicate but I guess it's not possible currently... To sum up:

1. Trigger the ```tl_page::generateAlias()``` and get the ```/contact```
2. Trigger the ```tl_page_folderpage::adjustAlias``` and get the ```contact```
3. Trigger the ```tl_page::generateAlias()``` with our alias value. On exception add the ID to our alias and trigger the method again. On exception display the error.

Would that be okay?

**Comment by aschempp** [comment]
Sounds reasonable…

**Comment by qzminski** [comment]
@Toflar can you confirm before I implement?

**Comment by Toflar** [comment]
Sounds good to me!

**Comment by qzminski** [comment]
Fixed in a536e62.
