### ISSUE TITLE
Website root changes to regular page automatically

### ISSUE THREAD

**Issue by swiss-netwalk** [terminal42/contao-folderpage#7]
If i create a "Website root" directly into a folder and save it, then it changes the "Website root" to a "Regular page" and loses for example the "DNS settings".
The "Website root" cannot be reselected, because it does not exist anymore.
When i create the "Website root" outside the folder and move it later into the folder, it still looks ok (the Icon) but when i edit the pagesettings, then in the "Page Type dropdown" it's marked "Regular page" and not "Website root", as it should. 
It's no possibility to move the sitestructure outside the Folder (to redefine for example) - it can only moved into other folders, but not outside
Contao 3.5.3 | folderpage 1.1.5

**Comment by aschempp** [comment]
@qzminski I was not aware that Contao core manually checks and changes the type of pages when in root or not… can you check and override that for FolderPage? Should be a Hotfix anyway, but be aware that *master* is Contao 3 and *develop* is Contao 4.

**Comment by qzminski** [comment]
@swiss-netwalk can you try 632cb80d369e28e167fc365ba4faf5973deef83f?

**Comment by swiss-netwalk** [comment]
i have try it, and it looks good :)
i checked the issued i had and everything works fine now.

is there a way to easy download the file "tl_page.php"? i dont have found a button or so
i have copy the code, pasted into Notepad++ and then save it....
it works, but i think there must be an easyer way :)

**Comment by qzminski** [comment]
I will merge it soon and release a new version.
