### ISSUE TITLE
Contao 4 Kompatibilität

### ISSUE THREAD

**Issue by sebssch** [terminal42/contao-folderpage#8]
Hallo,
ist eine Version für Contao 4.4 geplant?

**Comment by aschempp** [comment]
Für Contao 4+ musst du aktuell den Develop-Branch verwenden (`dev-develop` als Version manuell eingeben bei der Installation über den Contao Manager).

**Comment by sebssch** [comment]
Danke für die schnelle Antwort - werd ich gleich mal probieren.

**Comment by Ainschy** [comment]
Installation hat so weit geklappt.
Die Ordner werden im BE auch als Folder dargestellt, aber im FE nicht.

**Comment by aschempp** [comment]
FolderPage ist auch nur für's BE und nicht für's Frontend…

**Comment by Ainschy** [comment]
OK, dann funktioniert sie wie sie soll. Ich suche die Funktion, Seiten in einem Ordner zu organisieren ohne das der Ordner selbst als Seite aufrufbar ist, aber in einer mehrstufigen Navigation im FE auftaucht.
Danke.

**Comment by sebssch** [comment]
Hat bei mir prima geklappt. Macht was es soll.
Backend ist nun auch unter 4.4 schön aufgeräumt.

**Comment by aschempp** [comment]
> Ich suche die Funktion, Seiten in einem Ordner zu organisieren ohne das der Ordner selbst als Seite aufrufbar ist, aber in einer mehrstufigen Navigation im FE auftaucht.

Dazu musst du einfach Weiterleitungsseiten verwenden, denn sie werden in der Navigation immer sichtbar sein, sonst kann eine mehrstufige Navi gar nicht funktionieren.

**Comment by aschempp** [comment]
Ich habe die 2.0.0 soeben veröffentlicht, sollte nun also auch ohne *dev* installierbar sein.

**Comment by fritzmg** [comment]
> Dazu musst du einfach Weiterleitungsseiten verwenden, denn sie werden in der Navigation immer sichtbar sein, sonst kann eine mehrstufige Navi gar nicht funktionieren.

The old [contao-m17PageFolders](https://github.com/may17/contao-m17PageFolders) extension provides that functionality. Using redirect pages is not ideal, since you cannot easily distinguish between regular redirect pages and page "folders" within the navigation menu template (without assigning additional properties, like a CSS class or whatever).

Imho the folderpage of this extension should also be visible in regular navigation modules.
