### ISSUE TITLE
index-Alias lässt sich mit übergeordneten Ordner nicht aufrufen

### ISSUE THREAD

**Issue by akroii** [terminal42/contao-folderpage#9]
Wenn man einen Ordner in der obersten Ebene anlegt und darin die Startseite mit dem üblichen "index"-Alias hinterlegt, wird im Frontend der Alias des Ordners aufgerufen, statt der Startseite.

Backend:

<img width="326" alt="bildschirmfoto 2017-12-02 um 16 42 07" src="https://user-images.githubusercontent.com/8830861/33517187-cfe8606a-d77f-11e7-90eb-fed5933c6d8d.png">

Startseite in der Seitenstruktur:
<img width="699" alt="bildschirmfoto 2017-12-02 um 16 42 18" src="https://user-images.githubusercontent.com/8830861/33517190-daca688e-d77f-11e7-8a35-87a22cd0c4e3.png">

Im Frontend:

<img width="719" alt="bildschirmfoto 2017-12-02 um 16 44 53" src="https://user-images.githubusercontent.com/8830861/33517213-2f4de188-d780-11e7-8499-73a5ee5da7de.png">
(Hier erhält man eine leere, weiße Seite)

**Comment by fritzmg** [comment]
Soweit ich weiß unterstützt Contao keine Startseiten, die sich nicht in der obersten Ebene befinden.

**Comment by aschempp** [comment]
This is a known limitation of Contao. I don't think we can change that.
